# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=100)),
                ('good_img', models.CharField(max_length=2000)),
                ('good_category', models.CharField(max_length=100)),
                ('good_category_name', models.CharField(max_length=100)),
                ('good_id', models.CharField(max_length=200)),
                ('pic_id', models.IntegerField()),
                ('isNew', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'xm_category_goods',
            },
        ),
        migrations.CreateModel(
            name='Category_nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_id', models.IntegerField(unique=True)),
                ('nav_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'xm_category_nav',
            },
        ),
        migrations.CreateModel(
            name='deep_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('nav_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm.Category_nav', to_field='nav_id')),
            ],
            options={
                'db_table': 'xm_category_deep_category',
            },
        ),
        migrations.CreateModel(
            name='Recommend_pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=1000)),
                ('category_name', models.CharField(max_length=50)),
                ('rpic_id', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm.Category_nav', to_field='nav_id')),
            ],
            options={
                'db_table': 'xm_category_recommend_pic',
            },
        ),
        migrations.AddField(
            model_name='category_goods',
            name='good_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm.Category_nav', to_field='nav_id'),
        ),
    ]
